  spring:
    datasource:
      database: org.hibernate.dialect.H2Dialect
      url: jdbc:h2:mem:encarteiramento
      username: sa
      password: password
    jackson:
      deserialization:
        fail-on-unknown-properties: true
      date-format: yyyy-MM-dd
    jpa:
      show-sql: true
